# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${file(./local.yml):organisation}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: rpg-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: rpg-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: ${file(./local.yml):iamRole}
    
functions:
  CreateCharacters:
    handler: functions/CreateCharacter/index.handler
    events:
      - httpApi:
          path: /character
          method: get
  GetEnemy:
    handler: functions/GetEnemy/index.handler
    events:
      - httpApi:
          path: /enemy
          method: get
  GetLoot:
    handler: functions/GetLoot/index.handler
    events:
      - httpApi:
          path: /loot/{id}
          method: get
